### ISSUE TITLE
Error on import moviepy

### ISSUE THREAD

**Issue by QilinGu** [udacity/CarND-Term1-Starter-Kit-Test#4]
On Mac OS X 10.11.2. Followed the instruction to create conda envrionment using .yml file without any problem. But when running the test jupyter notebook, under "Test Moviepy" section, there was an NeedDownloadError showing up, saying ffmpeg.osx needs to be downloaded. It turns out moviepy repo has the similar issue, and the solution is adding the following two lines before importing moviepy:

`import imageio`
`imageio.plugins.ffmpeg.download()`

**Comment by mvirgo** [comment]
Added this - thanks for pointing it out!
