### ISSUE TITLE
Movie fails to play using Docker + Safari on OSX

### ISSUE THREAD

**Issue by jcsoo** [udacity/CarND-Term1-Starter-Kit-Test#5]
On OSX, the embedded video does not load if using Safari with the Docker environment. The video does work if using Safari + Anaconda, and also Firefox + Docker.

This is most likely related to https://github.com/jupyter/notebook/issues/1024 and https://stackoverflow.com/questions/27712778/video-plays-in-other-browsers-but-not-safari - Safari uses HTTP Range requests when loading videos, which is not supported by the Jupyter web server. I'm guessing that when using Anaconda, the Jupyter notebook is using a local file URL which would not have the same restriction.

I don't think this is anything that can be fixed, but it might be nice to add a note to use Firefox or Chrome when using the Docker image on OSX.

**Comment by ebraminio** [comment]
This can be closed now I guess.

**Comment by mvirgo** [comment]
Closing out since issue not with this repository.
